### ISSUE TITLE
Unzipping overwrites all files

### ISSUE THREAD

**Issue by hajducsekb** [hajducsekb/rvgl-randomizer#3]
The default method for unzipping in Python overwrites the tracks and cars, so we should still look into how it could be
a) prompted
b) never overwritten.

On Linux and MacOS, this could be solved with the unzip commnd, but we're looking for a crossplatform solution

**Comment by hajducsekb** [comment]
**Idea:** Extract files to an _/.../rvgl/temp_ folder, then they can be handled more precisely using python's file management tools (using `import os`, or other means which we find best).

**Comment by DVark09** [comment]
lol

**Comment by hajducsekb** [comment]
Solved with commit c48eaa26dd083d6a8b4c8f0810dfeff293c9fb89
